Fix uzem so it compiles under GCC 12
Summary:
 - There is an error when building uzem

In file included from avr8.h:33,
                 from uzem.cpp:27:
gdbserver.h:118:58: error: reference to ‘byte’ is ambiguous
  118 |         void avr_core_flash_write_hi8(unsigned int addr, byte val) ;
      |                                                          ^~~~
In file included from /usr/include/c++/12.1.1/bits/stl_algobase.h:61,
                 from /usr/include/c++/12.1.1/vector:60,
                 from avr8.h:29:
/usr/include/c++/12.1.1/bits/cpp_type_traits.h:406:30: note: candidates are: ‘enum class std::byte’
  406 |   enum class byte : unsigned char;
      |                              ^~~~
gdbserver.h:57:17: note:                 ‘typedef uint8_t byte’
   57 | typedef uint8_t byte;
      |                 ^~~~

Changes:
 - Modify typedefs used by the gdbserver component so they do not
   conflict.

Testing:
 - Used avr-gdb to verify I can debug into a Uzebox game

sudo apt install gdb-avr

(In Terminal 1)
cd uzebox
./bin/uzem --gdbserver -d MY_GAMES/circuit/default/circuit.uze

(In Terminal 2)
cd uzebox/MY_GAMES/circuit
avr-gdb default/circuit.elf

GNU gdb (GDB) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=avr".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from default/circuit.elf...
(gdb) target remote localhost:1284
Remote debugging using localhost:1284
0x00000000 in __vectors ()
(gdb) l
4914      }
4915
4916      ClearVram();
4917      SetTileTable(tileset);
4918
4919      SetUserRamTilesCount(GAME_USER_RAM_TILES_COUNT);
4920      StopSong();
4921      InitMusicPlayer(patches);
4922      StartSong(midisong);
4923      StopSong();
(gdb) b InitMusicPlayer
Breakpoint 1 at 0xa45a: file ../../../kernel/uzeboxSoundEngine.c, line 295.
(gdb) c
Continuing.

Breakpoint 1, InitMusicPlayer (patchPointersParam=0x803432) at ../../../kernel/uzeboxSoundEngine.c:295
295             patchPointers=patchPointersParam;
(gdb) l
290
291     const Patch *patchPointers;
292
293     void InitMusicPlayer(const Patch *patchPointersParam){
294
295             patchPointers=patchPointersParam;
296
297             masterVolume=DEFAULT_MASTER_VOL;
298
299     #if MIDI_IN == ENABLED
(gdb) bt